#!/bin/sh
# The analysis tools under script/ carry their own selftests, and nothing
# ran them. hammer2-core-diff.py, hammer2-provenance.py and
# hammer2-spin-audit.py each falsify the readings they print with a
# --selftest, the provenance CSV in doc/research/ is generated by one of
# them, and none of the three was named by a gate, the pre-push hook or
# CI. The rule test-inventory.sh enforces for test/, that being named and
# being run are different properties, applied to the tools that produce
# this tree's research readings.
#
# The population is every script/*.py whose source handles --selftest. It
# is asserted non-empty, so a sweep that matched nothing fails rather than
# passing. Each runs under `python3 -I`, isolated from the user's site
# packages and the current directory, because the result is a claim about
# the tool rather than about whatever this machine has installed.
#
# Exit 2 without python3. Exit 1 on any selftest that fails.
set -u
cd "$(dirname "$0")/.." || exit 2
command -v python3 >/dev/null 2>&1 || { echo "tools: COULD-NOT-RUN: no python3"; exit 2; }

fail=0 n=0
for t in script/*.py; do
	command grep -q -- '--selftest' "$t" || continue
	n=$((n + 1))
	out=$(python3 -I "$t" --selftest 2>&1)
	s=$?
	if [ "$s" -eq 0 ]; then
		echo "  ok    $(basename "$t"): $(printf '%s\n' "$out" | tail -1)"
	else
		echo "  FAIL  $(basename "$t"): selftest exited $s"
		printf '%s\n' "$out" | tail -5 | sed 's/^/        /'
		fail=$((fail + 1))
	fi
done
[ "$n" -gt 0 ] || { echo "tools: FAIL: no script/*.py carries a selftest at all" >&2; exit 1; }
echo "tools: $n tool selftest(s), $fail failed"
[ "$fail" -eq 0 ]
